services:
  - type: web
    name: hl-tracker
    runtime: node
    plan: free
    buildCommand: npm install --prefix frontend --include=dev && npm run --prefix frontend build && npm install --prefix backend --include=dev && npm run --prefix backend build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        sync: false
